#!/bin/bash

modprobe libcomposite

# https://eleccelerator.com/tutorial-about-usb-hid-report-descriptors/


cd /sys/kernel/config/usb_gadget/
mkdir -p g1
cd g1

echo 0x05ac > idVendor  # Apple, Inc.
echo 0x024f > idProduct # Aluminium Keyboard (ANSI)
echo 0x0100 > bcdDevice # v1.0.0
echo 0x0200 > bcdUSB    # USB2

STRINGS_DIR="strings/0x409"
mkdir -p "$STRINGS_DIR"
echo "6b65796d696d6570690" > "${STRINGS_DIR}/serialnumber"
echo "Apple, Inc." > "${STRINGS_DIR}/manufacturer"
echo "Aluminum Keyboard" > "${STRINGS_DIR}/product"

# Keyboard
KEYBOARD_FUNCTIONS_DIR="functions/hid.keyboard"
mkdir -p "$KEYBOARD_FUNCTIONS_DIR"
echo 1 > "${KEYBOARD_FUNCTIONS_DIR}/protocol" # Keyboard
echo 1 > "${KEYBOARD_FUNCTIONS_DIR}/subclass" # Boot interface subclass
echo 8 > "${KEYBOARD_FUNCTIONS_DIR}/report_length"

# Write the second report descriptor
D=$(mktemp)
{
  echo -ne \\x05\\x01        # Usage Page (Generic Desktop Ctrls)
  echo -ne \\x09\\x06        # Usage (Keyboard)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x05\\x07        #   Usage Page (Kbrd/Keypad)
  echo -ne \\x19\\xE0        #   Usage Minimum (0xE0)
  echo -ne \\x29\\xE7        #   Usage Maximum (0xE7)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x25\\x01        #   Logical Maximum (1)
  echo -ne \\x95\\x08        #   Report Count (8)
  echo -ne \\x75\\x01        #   Report Size (1)
  echo -ne \\x81\\x02        #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x95\\x01        #   Report Count (1)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x81\\x01        #   Input (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x95\\x05        #   Report Count (5)
  echo -ne \\x75\\x01        #   Report Size (1)
  echo -ne \\x05\\x08        #   Usage Page (LEDs)
  echo -ne \\x19\\x01        #   Usage Minimum (Num Lock)
  echo -ne \\x29\\x05        #   Usage Maximum (Kana)
  echo -ne \\x91\\x02        #   Output (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
  echo -ne \\x95\\x01        #   Report Count (1)
  echo -ne \\x75\\x03        #   Report Size (3)
  echo -ne \\x91\\x01        #   Output (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
  echo -ne \\x05\\x07        #   Usage Page (Kbrd/Keypad)
  echo -ne \\x19\\x00        #   Usage Minimum (0x00)
  echo -ne \\x2A\\xFF\\x00  #   Usage Maximum (0xFF)
  echo -ne \\x95\\x05        #   Report Count (5)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x26\\xFF\\x00  #   Logical Maximum (255)
  echo -ne \\x81\\x00        #   Input (Data,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x05\\xFF        #   Usage Page (Reserved 0xFF)
  echo -ne \\x09\\x03        #   Usage (0x03)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x95\\x01        #   Report Count (1)
  echo -ne \\x81\\x02        #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x05\\xC0        #   Usage Page (Reserved 0xC0)
  echo -ne \\x09\\x00        #   Usage (0x00)
  echo -ne \\x15\\x80        #   Logical Minimum (-128)
  echo -ne \\x25\\x7F        #   Logical Maximum (127)
  echo -ne \\x95\\x40        #   Report Count (64)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\xB1\\x02        #   Feature (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
  echo -ne \\xC0              # End Collection
} >> "$D"
cp "$D" "${KEYBOARD_FUNCTIONS_DIR}/report_desc"



# Second Keyboard Interface
KEYBOARD_FUNCTIONS_DIR_2="functions/hid.keyboard2"
mkdir -p "$KEYBOARD_FUNCTIONS_DIR_2"
echo 1 > "${KEYBOARD_FUNCTIONS_DIR_2}/protocol" # Keyboard
echo 1 > "${KEYBOARD_FUNCTIONS_DIR_2}/subclass" # Boot interface subclass
echo 8 > "${KEYBOARD_FUNCTIONS_DIR_2}/report_length"

# Write the first report descriptor
D=$(mktemp)
{
  echo -ne \\x06\\x01\\x00  # Usage Page (Generic Desktop Ctrls)
  echo -ne \\x09\\x80        # Usage (Sys Control)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x01        #   Report ID (1)
  echo -ne \\x19\\x81        #   Usage Minimum (Sys Power Down)
  echo -ne \\x29\\x83        #   Usage Maximum (Sys Wake Up)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x25\\x01        #   Logical Maximum (1)
  echo -ne \\x95\\x03        #   Report Count (3)
  echo -ne \\x75\\x01        #   Report Size (1)
  echo -ne \\x81\\x02        #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x95\\x01        #   Report Count (1)
  echo -ne \\x75\\x05        #   Report Size (5)
  echo -ne \\x81\\x01        #   Input (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\xC0              # End Collection

  echo -ne \\x05\\x0C        # Usage Page (Consumer)
  echo -ne \\x09\\x01        # Usage (Consumer Control)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x02        #   Report ID (2)
  echo -ne \\x19\\x00        #   Usage Minimum (Unassigned)
  echo -ne \\x2A\\xFF\\x02  #   Usage Maximum (0x02FF)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x26\\xFF\\x7F  #   Logical Maximum (32767)
  echo -ne \\x95\\x01        #   Report Count (1)
  echo -ne \\x75\\x10        #   Report Size (16)
  echo -ne \\x81\\x00        #   Input (Data,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\xC0              # End Collection

  echo -ne \\x06\\x00\\xFF  # Usage Page (Vendor Defined 0xFF00)
  echo -ne \\x09\\x01        # Usage (0x01)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x03        #   Report ID (3)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x26\\xFF\\x00  #   Logical Maximum (255)
  echo -ne \\x09\\x2F        #   Usage (0x2F)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x95\\x03        #   Report Count (3)
  echo -ne \\x81\\x02        #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\xC0              # End Collection

  echo -ne \\x05\\x01        # Usage Page (Generic Desktop Ctrls)
  echo -ne \\x09\\x06        # Usage (Keyboard)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x04        #   Report ID (4)
  echo -ne \\x05\\x07        #   Usage Page (Kbrd/Keypad)
  echo -ne \\x19\\x04        #   Usage Minimum (0x04)
  echo -ne \\x29\\x70        #   Usage Maximum (0x70)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x25\\x01        #   Logical Maximum (1)
  echo -ne \\x75\\x01        #   Report Size (1)
  echo -ne \\x95\\x78        #   Report Count (120)
  echo -ne \\x81\\x02        #   Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\xC0              # End Collection

  echo -ne \\x06\\x00\\xFF  # Usage Page (Vendor Defined 0xFF00)
  echo -ne \\x09\\x01        # Usage (0x01)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x05        #   Report ID (5)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x26\\xFF\\x00  #   Logical Maximum (255)
  echo -ne \\x19\\x01        #   Usage Minimum (0x01)
  echo -ne \\x29\\x02        #   Usage Maximum (0x02)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x95\\x05        #   Report Count (5)
  echo -ne \\xB1\\x02        #   Feature (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
  echo -ne \\xC0              # End Collection

  echo -ne \\x06\\x00\\xFF  # Usage Page (Vendor Defined 0xFF00)
  echo -ne \\x09\\x01        # Usage (0x01)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x06        #   Report ID (6)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x26\\xFF\\x00  #   Logical Maximum (255)
  echo -ne \\x19\\x01        #   Usage Minimum (0x01)
  echo -ne \\x29\\x02        #   Usage Maximum (0x02)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x96\\x07\\x04  #   Report Count (1031)
  echo -ne \\xB1\\x02        #   Feature (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
  echo -ne \\xC0              # End Collection

  echo -ne \\x05\\x01        # Usage Page (Generic Desktop Ctrls)
  echo -ne \\x09\\x02        # Usage (Mouse)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x07        #   Report ID (7)
  echo -ne \\x09\\x01        #   Usage (Pointer)
  echo -ne \\xA1\\x00        #   Collection (Physical)
  echo -ne \\x05\\x09        #     Usage Page (Button)
  echo -ne \\x15\\x00        #     Logical Minimum (0)
  echo -ne \\x25\\x01        #     Logical Maximum (1)
  echo -ne \\x19\\x01        #     Usage Minimum (0x01)
  echo -ne \\x29\\x05        #     Usage Maximum (0x05)
  echo -ne \\x75\\x01        #     Report Size (1)
  echo -ne \\x95\\x05        #     Report Count (5)
  echo -ne \\x81\\x02        #     Input (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x95\\x03        #     Report Count (3)
  echo -ne \\x81\\x01        #     Input (Const,Array,Abs,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x05\\x01        #     Usage Page (Generic Desktop Ctrls)
  echo -ne \\x16\\x00\\x80  #     Logical Minimum (-32768)
  echo -ne \\x26\\xFF\\x7F  #     Logical Maximum (32767)
  echo -ne \\x09\\x30        #     Usage (X)
  echo -ne \\x09\\x31        #     Usage (Y)
  echo -ne \\x75\\x10        #     Report Size (16)
  echo -ne \\x95\\x02        #     Report Count (2)
  echo -ne \\x81\\x06        #     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x15\\x81        #     Logical Minimum (-127)
  echo -ne \\x25\\x7F        #     Logical Maximum (127)
  echo -ne \\x09\\x38        #     Usage (Wheel)
  echo -ne \\x75\\x08        #     Report Size (8)
  echo -ne \\x95\\x01        #     Report Count (1)
  echo -ne \\x81\\x06        #     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\x05\\x0C        #     Usage Page (Consumer)
  echo -ne \\x0A\\x38\\x02  #     Usage (AC Pan)
  echo -ne \\x95\\x01        #     Report Count (1)
  echo -ne \\x81\\x06        #     Input (Data,Var,Rel,No Wrap,Linear,Preferred State,No Null Position)
  echo -ne \\xC0              #   End Collection
  echo -ne \\xC0              # End Collection

  echo -ne \\x06\\x00\\xFF  # Usage Page (Vendor Defined 0xFF00)
  echo -ne \\x09\\x01        # Usage (0x01)
  echo -ne \\xA1\\x01        # Collection (Application)
  echo -ne \\x85\\x08        #   Report ID (8)
  echo -ne \\x15\\x00        #   Logical Minimum (0)
  echo -ne \\x26\\xFF\\x00  #   Logical Maximum (255)
  echo -ne \\x09\\x00        #   Usage (0x00)
  echo -ne \\x75\\x08        #   Report Size (8)
  echo -ne \\x96\\x7D\\x01  #   Report Count (381)
  echo -ne \\xB1\\x02        #   Feature (Data,Var,Abs,No Wrap,Linear,Preferred State,No Null Position,Non-volatile)
  echo -ne \\xC0              # End Collection
} >> "$D"
cp "$D" "${KEYBOARD_FUNCTIONS_DIR_2}/report_desc"


CONFIG_INDEX=1
CONFIGS_DIR="configs/c.${CONFIG_INDEX}"
mkdir -p "$CONFIGS_DIR"
echo 500 > "${CONFIGS_DIR}/MaxPower"

CONFIGS_STRINGS_DIR="${CONFIGS_DIR}/strings/0x409"
mkdir -p "$CONFIGS_STRINGS_DIR"
echo "Config ${CONFIG_INDEX}: ECM network" > "${CONFIGS_STRINGS_DIR}/configuration"

ln -s "$KEYBOARD_FUNCTIONS_DIR" "${CONFIGS_DIR}/"
ln -s "$KEYBOARD_FUNCTIONS_DIR_2" "${CONFIGS_DIR}/"
ls /sys/class/udc > UDC

chmod 777 /dev/hidg0 # Keyboard
chmod 777 /dev/hidg1 # Keyboard2

sh /home/pi/pizero-usb-hid-keyboard/sendkeys f4



